[package]
name = "pokereval_cactus"
description = "A Rust version of the python poker hand evaluation library treys"
license = "MIT"
version = "0.1.0"
authors = ["Henrik BÃ¶ving <hargonix@gmail.com>"]
edition = "2018"


[dependencies]
rand = "0.6.5"
itertools = "0.8.0"